### Creates a new patient entity
POST http://localhost:33417/patients
Content-Type: application/json

{
  "name": "John Doe with Billing Account with kafka producer and consumer",
  "email": "johndoe3_with_billing_account_with_kafka_producer_and_consumer@gmail.com",
  "address": "123 main street",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"
}

###